general.import = [
    "~/.config/alacritty/themes/catppuccin_mocha.toml"
    ]

[env]
TERM = "xterm-256color"



[font]
size = 11.0
offset.y = -2
offset.x = 0
## Fonts are provided in the dotfiles repo!
[font.normal]
family = "SpaceMono Nerd Font"
style = "Regular"

[font.bold]
family = "SpaceMono Nerd Font"
style = "Bold"

[font.italic]
family = "SpaceMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "VictorMono Nerd Font"
style = "Bold Italic"

[window]
padding.x = 5
padding.y = 5
decorations = "Buttonless" 
##opacity = 0.8
#blur = true
[colors]
transparent_background_colors = true


